export const columnLabelsByResource: Record<string, Record<string, string>> = {
  authors: {
    photoUrl: 'Foto',
    name: 'Nombre',
    nationality: 'Nacionalidad',
    birthDate: 'Fecha nacimiento',
    status: 'Estado',
  },
  books: {
    isbn: 'ISBN',
    coverUrl: 'Portada',
    title: 'Título',
    category: 'Categoría',
    publisher: 'Editorial',
    language: 'Idioma',
    copiesLoaned: 'Prestados',
    copiesAvailable: 'Disponibles',
    status: 'Estado',
  },
  copies: {
    code: 'Código',
    book: 'Libro',
    shelf: 'Estantería',
    floor: 'Piso',
    location: 'Ubicación',
    status: 'Estado',
    condition: 'Condición',
  },
  categories: {
    name: 'Nombre',
    level: 'Nivel',
    description: 'Descripción',
    status: 'Estado',
  },
  loans: {
    code: 'Código',
    readerCode: 'Cód. lector',
    reader: 'Lector',
    loanDate: 'Fecha préstamo',
    items: 'Ejemplares',
    statusCounts: 'Estados',
  },
  reservations: {
    code: 'Código',
    readerCode: 'Cód. lector',
    reader: 'Lector',
    copyCode: 'Cód. ejemplar',
    reservationDate: 'Fecha reserva',
    status: 'Estado',
  },
  fines: {
    code: 'Código',
    loanCode: 'Cód. préstamo',
    copyCode: 'Cód. ejemplar',
    amount: 'Monto',
    daysLate: 'Días retraso',
    status: 'Estado',
    issuedAt: 'Fecha emisión',
  },
  payments: {
    code: 'Código',
    fineCount: 'Multas',
    readerCode: 'Cód. lector',
    reader: 'Lector',
    amount: 'Monto',
    paymentDate: 'Fecha pago',
    method: 'Método',
  },
  publishers: {
    photoUrl: 'Foto',
    name: 'Nombre',
    nationality: 'Nacionalidad',
    website: 'Sitio web',
    address: 'Dirección',
    status: 'Estado',
  },
  locations: {
    name: 'Nombre',
    description: 'Descripción',
    shelves: 'Estantes',
    books: 'Libros',
    copies: 'Ejemplares',
  },
  readers: {
    code: 'Código',
    fullName: 'Nombre',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    type: 'Tipo',
    status: 'Estado',
  },
  workers: {
    profilePhotoUrl: 'Foto',
    username: 'Nombre usuario',
    email: 'Correo electrónico',
    fullName: 'Nombre',
    role: 'Rol',
    status: 'Estado',
  },
  roles: {
    name: 'Nombre',
    description: 'Descripción',
    permissions: 'Permisos',
  },
}

export function getColumnLabel(resource: string | undefined, columnId: string): string {
  if (!resource) return columnId
  return columnLabelsByResource[resource]?.[columnId] ?? columnId
}
