-- Business codes (LEC-2026-00001, PRE-20261002-00001, ...) are now generated by the
-- application (CodeGenerator) from an atomic per-series, per-period counter.
--
-- The previous triggers computed MAX(code) + 1, which is not safe under concurrent
-- inserts, and generate_loan_code() parsed the counter from the wrong offset, so the
-- third loan of a day collided with the first one.

CREATE TABLE code_sequences (
    series     VARCHAR(10) NOT NULL,
    period     VARCHAR(8)  NOT NULL,
    last_value BIGINT      NOT NULL CHECK (last_value > 0),
    PRIMARY KEY (series, period)
);

-- Continue every counter from the codes that already exist.
INSERT INTO code_sequences (series, period, last_value)
SELECT series, period, GREATEST(MAX(counter), 1)
FROM (
    SELECT split_part(code, '-', 1) AS series, split_part(code, '-', 2) AS period, split_part(code, '-', 3)::BIGINT AS counter FROM readers
    UNION ALL
    SELECT split_part(code, '-', 1), split_part(code, '-', 2), split_part(code, '-', 3)::BIGINT FROM copies
    UNION ALL
    SELECT split_part(code, '-', 1), split_part(code, '-', 2), split_part(code, '-', 3)::BIGINT FROM loans
    UNION ALL
    SELECT split_part(code, '-', 1), split_part(code, '-', 2), split_part(code, '-', 3)::BIGINT FROM reservations
    UNION ALL
    SELECT split_part(code, '-', 1), split_part(code, '-', 2), split_part(code, '-', 3)::BIGINT FROM fines
    UNION ALL
    SELECT split_part(code, '-', 1), split_part(code, '-', 2), split_part(code, '-', 3)::BIGINT FROM payments
) existing
WHERE series <> '' AND period <> ''
GROUP BY series, period;

DROP TRIGGER trg_generate_reader_code ON readers;
DROP TRIGGER trg_generate_copy_code ON copies;
DROP TRIGGER trg_generate_loan_code ON loans;
DROP TRIGGER trg_generate_reservation_code ON reservations;
DROP TRIGGER trg_generate_fine_code ON fines;
DROP TRIGGER trg_generate_payment_code ON payments;

DROP FUNCTION generate_reader_code();
DROP FUNCTION generate_copy_code();
DROP FUNCTION generate_loan_code();
DROP FUNCTION generate_reservation_code();
DROP FUNCTION generate_fine_code();
DROP FUNCTION generate_payment_code();

ALTER TABLE readers      ALTER COLUMN code SET NOT NULL;
ALTER TABLE copies       ALTER COLUMN code SET NOT NULL;
ALTER TABLE loans        ALTER COLUMN code SET NOT NULL;
ALTER TABLE reservations ALTER COLUMN code SET NOT NULL;
ALTER TABLE fines        ALTER COLUMN code SET NOT NULL;
ALTER TABLE payments     ALTER COLUMN code SET NOT NULL;
